### ISSUE TITLE
Impossible to create an accretion disc around a Jupiter Mass planet

### ISSUE THREAD

**Issue by Francyrad** [danieljprice/phantom#119]
Dear Professor Daniel Price

I was trying to create an accretion disk (SETUP=disc) around a Jupiter mass planet, with the outer radius of Callisto (this kind of argument is very poor in the literature). 
The disk is been created successfully, however the simulation doesn't start. It gives me the error: 

 Initial mass and box size (in code units):
  Total mass:       1.000207E+00
  x-Box size:       2.671967E-02
  y-Box size:       2.671620E-02
  z-Box size:       1.032527E-02
 
 Setting initial values (in code units) to verify conservation laws:
  Initial total energy:           1.932075E-01
  Initial angular momentum:       1.717967E-05
  Initial linear momentum:        4.131455E-24

-------->   TIME =    0.000    : full dump written to file giove_00000   <--------

 input file giove.in written successfully.

 ---> DELETING temporary dump file giove_00000.tmp <---

 FATAL ERROR! maketree: no particles or all particles dead/accreted

I leave you there the zip with the simulation settings

[jupiterdisk.zip](https://github.com/danieljprice/phantom/files/6244197/jupiterdisk.zip)

I think that this happens because Phantom is been built to create larger accretion disks and that normally this density create a sink particle? Is there a way to change that? Because in the .in file i can't see this option...

Let me know and thank you for your wonderful work!

Francesco

**Comment by AdamFenton** [comment]
Hi Francesco, 


I stumbled across your comment and thought I would weigh in. 

You can enable on the fly sink creation by including the icreatesinks = 1 flag in the .in file. Trying to run phantom with that enabled will then re-write the .in fileswith some new parameters relating to sink particle generation. The parameter  "rho_crit_cgs" defines the density above which a new sink particle is formed and you can change it there. 


However, I think the problem may be because in your .setup file you have the sink accretion radius set to 1 AU but your R_out is set to 0.01336 AU (i.e. all your particles start of inside your accretion radius)

I have attached a setup file (in .txt format so GitHub would accept it) and that seems to work okay my end.

[disc_setup.txt](https://github.com/danieljprice/phantom/files/6561459/disc_setup.txt)



Cheers, 
Adam

**Comment by Francyrad** [comment]
It works, thank you very much!!!
