### ISSUE TITLE
Incorrect sink ev file naming 

### ISSUE THREAD

**Issue by themikelau** [danieljprice/phantom#134]
Illustrative example:

With the following options in the infile:
```
logfile =  L3/dumps/L301.log   ! file to which output is directed
dumpfile =  L3/dumps/dump_00100   ! dump file to start from
```
When running Phantom v2021.0.0, the sink evfiles are named in the form of, e.g., `dumpSink0001N.ev`, instead of, e.g., `dumpSink0001N01.ev` for the first file and etc. This resulted in data loss where the subsequent runs replace `dumpSink0001N.ev` instead of creating `dumpSink0001N02.ev` and `dumpSink0001N03.ev`, etc.

However, the log files and ev files are named correctly, i.e., `L3/dumps/L301.log, L3/dumps/L302.log, ...` and `L3/dumps/L301.ev, L3/dumps/L302.ev, ...`

**Comment by jameswurster** [comment]
The naming of the sink files assumes that logfile and dump file use the same nomenclature, i.e. 
L3/dumps/L301.log and L3/dumps/L3_00100 or L3/dumps/dump01.log and L3/dumps/dump_00100
If not, then it is using incorrect string lengths when writing the sink file name.  

I'm not sure why I wrote it that way rather than just relying on the logfile.  Feel free to fix this.  The offending code is at the top of init_ptmass in ptmass.F90.

**Comment by themikelau** [comment]
Thanks @jameswurster ! I will try to fix this.
