### ISSUE TITLE
Accretion disks simulation's are impossibly slow when the star accretion radius is < 1 AU

### ISSUE THREAD

**Issue by Francyrad** [danieljprice/phantom#306]
Dear developers
I was setting up the simulation of a gas accretion disc. I agreed that, unwittingly, the middle of the discs of all my simulations were eaten by my star within 1 AU. To change this setting, I set my star’s accretion radius to a number less than 1 AU. I was able to form an accretion disk without a hole in the center.
The point is, because of this change, the simulation becomes impossibly slow. I can’t find a logical reason why, if there is a disk core around the star, the simulation should become very slow, with a CPU efficiency of 5%. Is this a bug?

I run the simulation with 1200000 particles and M1 Pro CPU

Thank you for your work and best regards

**Comment by Francyrad** [comment]
Sorry for my late response. These are the files presets. is there anything wrong, or, as you say, smaller portions of accretion disks requires more computational power?

Regarding slack, i'm subscribed to the mailing list, however i have not been added and i cannot login with my gmail or with my university account.

let me know



[](url)
![Schermata 2022-09-19 alle 13 19 35](https://user-images.githubusercontent.com/103508988/191006509-c73af318-3f09-4118-aa8a-a62fd2bd9070.png)
![Schermata 2022-09-19 alle 13 19 53](https://user-images.githubusercontent.com/103508988/191006511-0f3ad1f4-5f97-44ea-ab65-0e73f4e4721b.png)
![Schermata 2022-09-19 alle 13 20 14](https://user-images.githubusercontent.com/103508988/191006512-1afaad77-14f8-468d-97be-e1f896061931.png)

**Comment by jameswurster** [comment]
Hello
1) I have sent an invitation to the slack channel, so hopefully you can join.
2) Thank you for sending the files.  In the future, can you please paste in the text rather than an image so that I or another developer can directly use your files for testing.
3) Regarding your problem, there appears to be a few inconsistencies/issues:
3a) It is a bad idea to set an inner disc radius of 1e-8 when your sink radius is 0.1 since all the gas from 1e-8 to 0.1 will immediately be accreted, changing the intended dynamics of your system.  I'm not sure of the exact typically gap, but one is normally left between the star and the edge of the disc, so try an inner disc radius of 0.2 or 0.5.   
3b) How did you set your dtmax?  Given that tmax = 1.1e5, I would have expected a reasonable dtmax to be on order 1.1e3.  I'm guessing with such a small dtmax that the majority of the time is spend writing dumpfiles, which will also be eating up your memory.  

Hopefully the changes in 3 will fix your problem.  If not, when you run Phantom, there is an output printed to the screen.  Please paste this in since there is useful diagnostic material in there.

Cheers & good luck
James
