### ISSUE TITLE
Remove metric as compile time option

### ISSUE THREAD

**Issue by dliptai** [danieljprice/phantom#358]
The metric should become a runtime option.

Currently, a user must recompile the code if they wish to use a different metric. e.g.
```
make METRIC=kerr
```

We'd like to compile all the metrics, and point to the one specified in the infile via a procedure pointer.

This will require:
- [ ] a new infile option (`metric`), including parsing/check of the option
- [ ] changing module names to e.g. `metric_kerr` `metric_schwarzschild`
- [ ] compiling all the metrics (change SRCS in Makefile)
- [ ] set the procedure pointer somewhere during the start of the simulation after the infile is read, maybe in init?

A working example of procedure pointers can be found in `readwrite_dumps.F90`

**Comment by dliptai** [comment]
@martinatoscani @msha0023

**Comment by dliptai** [comment]
See also https://github.com/danieljprice/splash/blob/4a0fef21ac6d23a0a57f5349ad1a82afc04079d8/src/kernels.f90#L66-L133

**Comment by danieljprice** [comment]
I am closing this as the reason for this issue was wanting to relax a star in the Minkowski metric and then switch to Kerr metric after relaxation. However I realised the same functionality can be achieved by simply setting M=0 in the metric during the relaxation procedure. This is now implemented in SETUP=grtde via #413
