### ISSUE TITLE
File format schema

### ISSUE THREAD

**Issue by dmentipl** [danieljprice/phantom#43]
I think it would be good to write up in the documentation a "schema" for the file format.

At the moment the only way to know what should be written to a file is by reading the source code of `readwrite_dumps.F90` or `readwrite_dumps_hdf5.F90`. I think we should write something in the documentation that outlines what should be written to file given a set of compile-time and run-time options.

E.g. if the compile-time option `DUST=yes` then `dustfrac` and `tstop` are written to file. In addition, if using the 1-fluid method (`use_dustfrac == .true.` which is set by reading the initial conditions dump file) then `deltav` is written to file.

**Comment by dmentipl** [comment]
Part of the reason why I think this would be useful is that without it it is hard to keep the HDF5 file format in parity with the native format.

**Comment by danieljprice** [comment]
For me the real issue here is that readwritedump_hdf5 is written at the wrong level, it should replace utils_dumpfiles as a low-level backend, not readwrite_dumps, which is meant to be the high level routine specifying what goes into the output files.

there is a lot of code that was cut and pasted into the readwritedump_hdf5 format, and this will continually go out of date as more physics is implemented in phantom

in the native format, readwrite_dumps does not write or read anything directly to disk, this is all done in the lower-level utils_dumpfiles.f90 routines. Those routines are agnostic about what the quantities actually are.

**Comment by dmentipl** [comment]
I see your point. I think it's just a little tricky to use the original readwrite_dumps routines because they have extra requirements such as blocks and tags. I've tried to tidy up the HDF5 code so that it's easy to see what arrays might be missing. So hopefully in the future it's easy enough, with a small amount of work, to keep the HDF5 format up to date with the native format. Feel free to close the issue if you think it's not worth pursuing a file-format schema in the future.
