### ISSUE TITLE
Possible double-counting in potential energy calculation

### ISSUE THREAD

**Issue by themikelau** [danieljprice/phantom#57]
In line 338 of energies.F90 in the compute_energies subroutine,
`if (gravity) epot = epot + poten(i)`,
the total potential energy appears to be calculated by summing the "poten" of each particle, which would double-count. We should check whether double-counting is also present in other instances where total potential energies are calculated.

**Comment by danieljprice** [comment]
this would be easy to check, e.g. just by setting up a uniform density sphere of particles and check that the potential energy is -3/5 GM^2/r. I would be very surprised if there is a factor of 2 off here. Adding such a check to the test_gravity module would be sensible anyway.

**Comment by danieljprice** [comment]
Update, I checked this and it is already tested in test_gravity anyway, because it compares the tree calculation of potential with the potential computed via direct summation. However, I added an extra check that the potential is also equal to -3/5 GM^2/R for this case, which I confirmed to be true. So no bug here.
